[profile.default]
solc_version = "0.8.26"
optimizer = true
optimizer_runs = 200
src = "src"
test = "test"
libs = ["lib"]
remappings = ["@openzeppelin/=lib/openzeppelin-contracts/"]

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
wrap_comments = true

[[profile.default.fs_permissions]]
access = "read"
path = "out"

[[profile.default.fs_permissions]]
access = "read-write"
path = "./deployments"

[coverage]
exclude = ["script/*"]